version: '3.9'
services:
  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  #NodeJS API service
  api:
    build: .
    ports:
      # - local machine port:container port
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb+srv://username:password@clustername.clusterid.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: products
      NAME: 
